name: Build Void Runner APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  export-android:
    runs-on: ubuntu-latest
    name: Export APK Godot
    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Exportar APK usando Godot 4.2.1
        uses: firebelley/godot-export@v6.0.0
        with:
          godot_version: 4.2.1
          export_debug: true
          export_preset: Android
          project_subpath: "."

      - name: Subir APK como Artefacto
        uses: actions/upload-artifact@v4
        with:
          name: VoidRunner-Android-APK
          path: |
            build/android/*.apk
            **/*.apk
          if-no-files-found: error
